config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles,  only: [:index, :new,:create]
  resources :messages,   only: [:index,:create]
  resources :rooms,  only: [:new,:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
  validates :nickname,presence: true
  validates :title,presence: true
  validates :text,presence: true
  validates :sex_id,presence: true
  validates :age,presence: true

  belongs_to :users
  
end

app/models/category.rb
class Category < ActiveHash::Base
 self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '専門家' },
 ]
  include ActiveHash::Associations
  has_many :articles
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content,presence: true
  validates :nickname, presence: true
  validates :room, presence: true

  belongs_to :users
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' }
  ]
  include ActiveHash::Associations
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :nickname, presence: true
  validates :email, presence: true
  validates :sex_id, presence: true
  validates :age, presence: true
  validates :encrypted_password, presence: true
  validates :category_id, presence:  true

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :articles
         has_many :rooms,through: :room_users
         has_many :room_users
         has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

     def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
    def configure_permitted_parameters 
      devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name,:last_name,:first_name_kana,:last_name_kana,:nickname,:sex_id,:age,:category_id])
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc)
  end
  def  new
    @articles = Article.new
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to  root_path
    else
      render :new
    end
  end
  
  private
  def article_params
    params.require(:article).permit(:nickname,:title,:text,:sex_id,:age).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = current_user.room
    @message = @room.messages.includes(:user)
  end
  def create
   @room = Room.find(params[:room_id])
   @message = @room.messages.new(message_params)
   if @message.save
    redirect_to room_messages_path(@room)
  else
    @messages = @room.messages.includes(:user)
   end
  end

  private
  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @rooms = Room.new
  end
  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end
  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name,user_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  
  end

   def update
    current_user.update(user_params)
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end

  private

  def user_params
    params.require(:user).parmit(:first_name,:last_name,:first_name_kana,:last_name_kana,:nickname,:sex_id,:age,:category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<!DOCTYPE HTML>
<html>
 <header>
      <% if user_signed_in? %>
        <div class="lists-left">
        <%= link_to "ログアウト",articles_path,method: :delete, class: "logout" %>
        <%= link_to "投稿する",new_article_path, class: "post"%>
        <%= link_to "チャットルーム",messages_path, class: "lists"%>
        </div>
       <% else %>
         <div class="list-right">
         <%= link_to "ログイン",new_user_session_path,class: "login"%>
         <%= link_to "新規登録",new_user_registration_path, class: "singup"%>
         </div>
       <% end %>
        <div class="image-header">
         <div class="image-top"  style="background:url(images/top.01.png); background-size:cover;">
         </div>
        </div>
   </header>
   <body>
      <div class="body-top-page">
        <div class="image-left"  style="background:url(images/top.003.png); background-size:cover;">
        </div>
        <div class="image-right"  style="background:url(images/top.002.png); background-size:cover;">
        </div>
       </div>
 </body>
</html>
 

app/views/articles/new.html.erb
<!--
templates/edit.html
記事編集ページ
-->
    <%#link rel="stylesheets" href="application.css" %>

<br>
<h1>MY Blog Name |管理人ページ</h1>
<p>こんにちは、{{name}}さん</p>
<link rel="stylesheets" href="article/articles.css">
<div class="main-container">
  <div class="admin-main-menu">
    <h2>新規投稿</h2>
    <div class="edit">
      <form action="/admin/add" method="post">
       <h3>タイトル</h3>
       <input type="text" name="title" value="">
       <h3>スラッグ</h3>
       <input type="text" name="slug" value="">
       <h3>内容</h3>
       <texttarea name="contents" id="contents"></textarea>
       <h3>カテゴリ</h3>
       <input type="radio" name="category" value="{{cat['slug']}}">{{cat['name']}}
       <h3>タグ</h3>
       <input type="checkbox" name="tags[]"value="{{tag['slug']}}">{{tag['name']}}
       <h3>詳細・抜粋</h3>
       <texttarea name="description" id="description"></textarea>
       <p>
         <button type="submit"name="draft" id="draft">下書き保存</button>
         <button type="submit"name="preview" value="preview" id="preview" formtarget="_blank">プレビュー</button>
         <button type="submit"name="release" value="release"id="release">公開</button>
        </p>
      </form>
    </div>
  </div>
  <div class="admin-side-menu">
    <h2>Menu</h2>
    <ul>
    <li><a href="/admin/user">ユーザー確認・編集</a></li>
    <li><a href="/admin/new">新規追加</a></li>
    <li><a href="/admin">投稿一覧</a></li>
    </ul>
  </div>
</div>
{% endblock %}

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
    <%= @room.name %>
    </div>
  </div>
  <div class="rigth-header">
    <div class="header-button">
   <%= link_to "チャットを終了する", room_path(@room),method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
 <%= render partial: 'message',collection: @messages %>
 </div>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>
  

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
   <div class="message-user">
   <%= message.user.name %>
  </div>
  <div class="message-date">
    <%= l message.create_at %>
  </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
     <%= message.content %>
     </div>
               <%#= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-ber">
  <div class="side-ber-header">
  <div class="header-name">
   <%= link_to current_user.name,new_room_path(current_user) %>
   <link rel="stylesheets" href="room/room.css">
  </div> 
  <div class="create-rooms">
        <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

  <div class="rooms">
  <% current_user.rooms.each do |room| %>
   <div class="room">
     <div class="room-name">
      <%= link_to room.name,room_messages_path(room) %>
    </div>
  </div>
 <% end %>
</div>
  </div>
  <div class="chat">
  <%= render "main_chat"%>
  </div>
</div>


<%#=チャットルームのボタンを押すとチャットを作成するのページにいく＝＞新規チャットルームのページ%>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select>
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.name %><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<% current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>